# Generated by Django 5.1.1 on 2025-03-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_preference', models.CharField(choices=[('vegan', 'Vegan'), ('keto', 'Keto'), ('vegetarian', 'Vegetarian'), ('omnivore', 'Omnivore')], default='omnivore', max_length=100)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('caloric_needs', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
